
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int R_COLUMN = 36;
  public static final int R_TITULO = 42;
  public static final int DOSPUNTOS = 3;
  public static final int PUNTOSDOBLE = 5;
  public static final int R_MUL = 22;
  public static final int PUNTOYCOMA = 2;
  public static final int R_MEDIA = 25;
  public static final int R_MOD = 24;
  public static final int R_LABEL = 49;
  public static final int CORCHETEC = 19;
  public static final int R_VALUES = 48;
  public static final int CORCHETEA = 18;
  public static final int R_PRINT = 35;
  public static final int R_EXEC = 47;
  public static final int IGUAL = 33;
  public static final int R_VARIANZA = 28;
  public static final int R_CONSOLE = 34;
  public static final int R_SUM = 20;
  public static final int R_END = 10;
  public static final int R_ARR = 17;
  public static final int R_CHAR = 8;
  public static final int ID = 7;
  public static final int R_HISTOGRAM = 41;
  public static final int EOF = 0;
  public static final int DECIMAL = 13;
  public static final int R_MAX = 29;
  public static final int ASIGNACION2 = 37;
  public static final int R_VAR = 6;
  public static final int error = 1;
  public static final int COMILLA = 14;
  public static final int COMA = 15;
  public static final int CADENA = 12;
  public static final int R_TITULOY = 46;
  public static final int R_EJEY = 44;
  public static final int R_TITULOX = 45;
  public static final int R_EJEX = 43;
  public static final int ASIGNACION = 4;
  public static final int R_RES = 21;
  public static final int R_PIE = 40;
  public static final int PARENTESIS_C = 32;
  public static final int PARENTESIS_A = 31;
  public static final int IDARR = 16;
  public static final int R_BAR = 38;
  public static final int R_DOUBLE = 9;
  public static final int R_MEDIANA = 26;
  public static final int R_LINE = 39;
  public static final int R_PROGRAM = 11;
  public static final int R_MODA = 27;
  public static final int R_DIV = 23;
  public static final int R_MIN = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "ASIGNACION",
  "PUNTOSDOBLE",
  "R_VAR",
  "ID",
  "R_CHAR",
  "R_DOUBLE",
  "R_END",
  "R_PROGRAM",
  "CADENA",
  "DECIMAL",
  "COMILLA",
  "COMA",
  "IDARR",
  "R_ARR",
  "CORCHETEA",
  "CORCHETEC",
  "R_SUM",
  "R_RES",
  "R_MUL",
  "R_DIV",
  "R_MOD",
  "R_MEDIA",
  "R_MEDIANA",
  "R_MODA",
  "R_VARIANZA",
  "R_MAX",
  "R_MIN",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "IGUAL",
  "R_CONSOLE",
  "R_PRINT",
  "R_COLUMN",
  "ASIGNACION2",
  "R_BAR",
  "R_LINE",
  "R_PIE",
  "R_HISTOGRAM",
  "R_TITULO",
  "R_EJEX",
  "R_EJEY",
  "R_TITULOX",
  "R_TITULOY",
  "R_EXEC",
  "R_VALUES",
  "R_LABEL"
  };
}

