package Inicio;



import Analizadores.Arbol;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import clases.*;
import java.io.StringReader;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author evams
 */
public class DataForge extends javax.swing.JFrame {

    /**
     * Creates new form DataForge
     */
    public DataForge() {
        initComponents();
        Consola.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Save1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jEliminar = new javax.swing.JMenu();
        Ejecutar = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        New1 = new javax.swing.JMenuItem();
        New2 = new javax.swing.JMenuItem();
        New3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consola");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ver Graficas");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Entrada");

        Consola.setEditable(false);
        Consola.setBackground(new java.awt.Color(255, 255, 255));
        Consola.setColumns(20);
        Consola.setForeground(new java.awt.Color(0, 0, 0));
        Consola.setRows(5);
        Consola.setMaximumSize(new java.awt.Dimension(200, 80));
        Consola.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(Consola);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Anterior");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Siguiente");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/findo.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(527, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(433, 433, 433)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        Archivo.setBackground(new java.awt.Color(255, 255, 255));
        Archivo.setForeground(new java.awt.Color(0, 0, 0));
        Archivo.setText("Archivo");
        Archivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArchivoMouseClicked(evt);
            }
        });

        New.setBackground(new java.awt.Color(255, 255, 255));
        New.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        New.setForeground(new java.awt.Color(0, 0, 0));
        New.setText("Nuevo Archivo");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        Archivo.add(New);

        Open.setBackground(new java.awt.Color(255, 255, 255));
        Open.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Open.setForeground(new java.awt.Color(0, 0, 0));
        Open.setText("Abrir Archivo");
        Open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMouseClicked(evt);
            }
        });
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        Archivo.add(Open);

        Save1.setBackground(new java.awt.Color(255, 255, 255));
        Save1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Save1.setForeground(new java.awt.Color(0, 0, 0));
        Save1.setText("Guardar");
        Save1.setActionCommand("Guardar ");
        Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save1ActionPerformed(evt);
            }
        });
        Archivo.add(Save1);

        jMenuBar1.add(Archivo);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Pestañas");
        jMenu2.setToolTipText("");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jEliminar.setForeground(new java.awt.Color(0, 0, 0));
        jEliminar.setText("Eliminar");
        jEliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(jEliminar);

        jMenuBar1.add(jMenu2);

        Ejecutar.setBackground(new java.awt.Color(255, 255, 255));
        Ejecutar.setForeground(new java.awt.Color(0, 0, 0));
        Ejecutar.setText("Ejecutar");
        Ejecutar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Ejecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EjecutarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Ejecutar);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setText("Reportes");
        jMenu4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        New1.setBackground(new java.awt.Color(255, 255, 255));
        New1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        New1.setForeground(new java.awt.Color(0, 0, 0));
        New1.setText("Reporte Token");
        New1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New1ActionPerformed(evt);
            }
        });
        jMenu4.add(New1);

        New2.setBackground(new java.awt.Color(255, 255, 255));
        New2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        New2.setForeground(new java.awt.Color(0, 0, 0));
        New2.setText("Reporte Errores");
        New2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New2ActionPerformed(evt);
            }
        });
        jMenu4.add(New2);

        New3.setBackground(new java.awt.Color(255, 255, 255));
        New3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        New3.setForeground(new java.awt.Color(0, 0, 0));
        New3.setText("Reporte Tabla Simbolos");
        New3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New3ActionPerformed(evt);
            }
        });
        jMenu4.add(New3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ArchivoMouseClicked

    private void OpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMouseClicked
        
    }//GEN-LAST:event_OpenMouseClicked

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
        String nuevo = JOptionPane.showInputDialog("Ingrese el nombre del nuevo archivo");
        if (nuevo != null && !nuevo.trim().isEmpty()) {
            //jTabbedPane1.addTab(nuevo, new JScrollPane(new JTextArea()));
            //jEliminar.add(nuevo);
             JMenuItem item = new JMenuItem(nuevo);
            item.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for (int i = jTabbedPane1.getTabCount() - 1; i >= 0; i--) {
                    if (nuevo.equals(jTabbedPane1.getTitleAt(i))) {
                        jTabbedPane1.removeTabAt(i);
                        jEliminar.remove(item);
                        JOptionPane.showMessageDialog(null, "Se cerró la pestaña: " + nuevo, "Pestaña Cerrada", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    }
                }
            }
        });
        jEliminar.add(item);
        jTabbedPane1.addTab(nuevo, new JScrollPane(new JTextArea()));
            
        }
    }//GEN-LAST:event_NewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EjecutarMouseClicked
        // TODO add your handling code here:
        Consola.setText(""); 
        arreglos_publicos.tokens.clear();
        arreglos_publicos.errores.clear();
        arreglos_publicos.contador=0;
        arreglos_publicos.contadorE=0;
        int indice = jTabbedPane1.getSelectedIndex();
        Component panelObtenido = jTabbedPane1.getComponentAt(indice);
        
        if (panelObtenido instanceof JScrollPane jScrollPane) {
            JTextArea selectedTextArea = (JTextArea)  jScrollPane.getViewport().getView();
            //System.out.println(selectedTextArea.getText());
            try {
                Analizadores.analizadorLexico lexer = new Analizadores.analizadorLexico(new StringReader(selectedTextArea.getText())); //para llamar impoprt o llamamo asi
                Analizadores.Parser parser = new Analizadores.Parser(lexer);
                Arbol arbol_sintactico = (Arbol)parser.parse().value; //Parseo el .value me devuelve el analizador sintactico
                //arbol_sintactico.printArbol(arbol_sintactico);
                //arbol_sintactico.guardarArbol(arbol_sintactico);
                //arbol_sintactico.printArbol(arbol_sintactico);
                Interprete interprete = new Interprete(arbol_sintactico);
                interprete.run();
                String respuesta = interprete.getConsola();
                
                Consola.setEditable(true);

                Consola.append(respuesta);
                Consola.setEditable(false);
                System.out.println(respuesta);
               //aqui debo mandar respuesta a Consola que es mi jtext area
            } catch (Exception e) {
                System.out.println("Error fatal en compilación de entrada.");
                System.out.println(e);
            }
        }

        System.out.println();
    }//GEN-LAST:event_EjecutarMouseClicked

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .df", "df"));
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
             try {
            String nombreArchivo = archivo.getName();
            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(archivo), StandardCharsets.UTF_8));
            StringBuilder contenido = new StringBuilder();
            String linea;
            while ((linea = reader.readLine()) != null) {
                contenido.append(linea).append("\n");
            }
            JTextArea textArea = new JTextArea();
            textArea.setText(contenido.toString());
            JScrollPane scrollPane = new JScrollPane(textArea);
            jTabbedPane1.addTab(nombreArchivo, scrollPane);
             JMenuItem item = new JMenuItem(nombreArchivo);
            item.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    for (int i = jTabbedPane1.getTabCount() - 1; i >= 0; i--) {
                        if (nombreArchivo.equals(jTabbedPane1.getTitleAt(i))) {
                            jTabbedPane1.removeTabAt(i);
                            jEliminar.remove(item);
                            JOptionPane.showMessageDialog(null, "Se cerró la pestaña: " + nombreArchivo, "Pestaña Cerrada", JOptionPane.INFORMATION_MESSAGE);
                            break;
                        }
                    }
                }
            });
            jEliminar.add(item);
            reader.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
  
    }//GEN-LAST:event_OpenActionPerformed

    private void Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save1ActionPerformed
         int indice = jTabbedPane1.getSelectedIndex();
        Component panelObtenido = jTabbedPane1.getComponentAt(indice);

        if (panelObtenido instanceof JScrollPane) {
            JTextArea selectedTextArea = (JTextArea) ((JScrollPane) panelObtenido).getViewport().getView();
            String contenido = selectedTextArea.getText();

            String nombrePestana = jTabbedPane1.getTitleAt(indice);
            if (!nombrePestana.endsWith(".df")) {
                nombrePestana += ".df";
            }

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .df", "df"));
            fileChooser.setSelectedFile(new File(nombrePestana));
            int seleccion = fileChooser.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooser.getSelectedFile();

                try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
                    writer.write(contenido);
                    JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_Save1ActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed

    }//GEN-LAST:event_jEliminarActionPerformed

    private void New1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New1ActionPerformed
        reportes.generarReporteTokens();
       
    }//GEN-LAST:event_New1ActionPerformed

    private void New2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New2ActionPerformed
         reportes.generarReporteErrores();
    }//GEN-LAST:event_New2ActionPerformed

    private void New3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataForge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataForge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataForge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataForge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataForge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JTextArea Consola;
    private javax.swing.JMenu Ejecutar;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem New1;
    private javax.swing.JMenuItem New2;
    private javax.swing.JMenuItem New3;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
